OpenKy.WebUI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using OpenKy.Domain.Abstract;
using OpenKy.Domain.Concrete;
using OpenKy.Domain.Entities;
using OpenKy.WebUI.Concrete;

namespace OpenKy.WebUI.Controllers
{
    [Auth(Roles = UserType.Staff | UserType.Professor)]
    public class CoursesController : Controller
    {
        private Repository db = new Repository();
        private ICourseProcessor course_proc;
        private IMemberProcessor member_proc;
        private ITypeDefineProcessor typedef_proc;
        private IDepartmentProcessor depart_proc;

        public CoursesController()
        {
            course_proc = new CourseProc(db);
            member_proc = new MemberProc(db);
            typedef_proc = new TypeDefineProc(db);
            depart_proc = new DepartmentProc(db);
        }

        // GET: Courses
        public ActionResult Index()
        {
            TypeDefine professor_type = typedef_proc.FindType("교수");
            var professors = member_proc.GetMembers(professor_type.Type);

            ViewBag.ProfessorList = professors;
            return View(course_proc.GetCourses());
        }

        // GET: Courses/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = course_proc.GetCourse(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        void PushDropdownListItem()
        {
            var lstProfessor = new List<SelectListItem>();
            TypeDefine professor_type = typedef_proc.FindType("교수");

            var professors = member_proc.GetMembers(professor_type.Type);
            if (professors.Any())
            {
                lstProfessor.AddRange(professors.Select(m => new SelectListItem()
                {
                    Text = m.Name + " (" + depart_proc.GetDepartment(m.Department).Name + ")", Value = m.Number
                }));
            }

            ViewBag.ProfessorList = lstProfessor;
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            PushDropdownListItem();
            return View();
        }

        // POST: Courses/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Code,Name,Divide,Professor,Credits,Theory,Training")] Course course)
        {
            if (ModelState.IsValid)
            {
                if (!course_proc.AddCourse(course))
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = course_proc.GetCourse(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            PushDropdownListItem();
            return View(course);
        }

        // POST: Courses/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Code,Name,Divide,Professor,Credits,Theory,Training")] Course course)
        {
            if (ModelState.IsValid)
            {
                course_proc.UpdateCourse(course.Code, course);
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = course_proc.GetCourse(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if(!course_proc.DeleteCourse(id))
                return new HttpNotFoundResult();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenKy.WebUI/Controllers/TimeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OpenKy.Domain.Abstract;
using OpenKy.Domain.Concrete;
using OpenKy.Domain.Entities;
using OpenKy.WebUI.Concrete;

namespace OpenKy.WebUI.Controllers
{
    [Auth(Roles = UserType.Staff | UserType.Professor)]
    public class TimeTablesController : Controller
    {
        private Repository db = new Repository();
        private ITimetableProcessor timetable_proc;
        
        public TimeTablesController()
        {
            timetable_proc = new TimeTableProc(db);
        }

        // GET: TimeTables
        public ActionResult Index(string id)    // id는 과목 코드
        {
            return View(db.TimeTable.Where(e=>e.Course == id).ToList());
        }

        // GET: TimeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTable.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // GET: TimeTables/Create
        public ActionResult Create()   // id는 과목 코드
        {
            return View();
        }

        // POST: TimeTables/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Year,Term,Course,Facility,Weekday,Period")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                // 입력된 시간에 겹치는 시간이 있는지 확인함.
                if (timetable_proc.IsOverlap(timeTable.Class, timeTable.Year, timeTable.Term, timeTable.Weekday, timeTable.Period))
                {
                    ModelState.AddModelError("PeriodOverlap", "해당 시간에 겹치는 교과목이 있습니다.");
                    return View(timeTable); // 겹친다!
                }

                db.TimeTable.Add(timeTable);
                db.SaveChanges();
                return RedirectToAction("Index", new {id=timeTable.Course});
            }

            return View(timeTable);
        }

        // GET: TimeTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTable.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // POST: TimeTables/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Year,Term,Course,Facility,Weekday,Period")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(timeTable);
        }

        // GET: TimeTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTable.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // POST: TimeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TimeTable timeTable = db.TimeTable.Find(id);
            db.TimeTable.Remove(timeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenKy.WebUI/Views/Courses/Create.cshtml
@model OpenKy.Domain.Entities.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Divide, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Divide, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Divide, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Professor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Professor, ViewBag.ProfessorList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Professor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Training, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Training, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Training, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OpenKy.WebUI/Views/Courses/Delete.cshtml
@model OpenKy.Domain.Entities.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Divide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Divide)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Professor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Professor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Training)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Training)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OpenKy.WebUI/Views/Courses/Details.cshtml
@model OpenKy.Domain.Entities.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Divide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Divide)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Professor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Professor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Theory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Theory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Training)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Training)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Code }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OpenKy.WebUI/Views/Courses/Edit.cshtml
@model OpenKy.Domain.Entities.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Code)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Divide, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Divide, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Divide, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Professor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Professor, ViewBag.ProfessorList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Professor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Theory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Theory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Theory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Training, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Training, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Training, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

OpenKy.WebUI/Views/Courses/Index.cshtml
@using OpenKy.Domain.Entities
@model IEnumerable<OpenKy.Domain.Entities.Course>

@{
    var professors = ViewBag.ProfessorList as IQueryable<Member>;
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Divide)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Professor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Credits)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Theory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Training)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Divide)
        </td>
        <td>
            @{
                var professor = professors.First(e => e.Number == item.Professor);
                @Html.Raw(professor.Name)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Credits)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Theory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Training)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Code }) |
            @Html.ActionLink("Details", "Details", new { id=item.Code }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Code }) |
            @Html.ActionLink("TimeTable", "Index", "TimeTables", new{ id = item.Code }, new { target = "_blank" })
        </td>
    </tr>
}

</table>
@if (!Model.Any())
{@Html.Raw("항목이 없습니다.")}