OpenKy.WebUI/Models/Member.cs
namespace OpenKy.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Member")]
    public partial class Member
    {
        [Key]
        [StringLength(20)]
        public string Number { get; set; }

        [Required]
        [StringLength(20)]
        public string Name { get; set; }

        [Required]
        [StringLength(16)]
        public string Phone { get; set; }

        [Required]
        [StringLength(100)]
        public string Email { get; set; }

        [Column(TypeName = "date")]
        public DateTime Birthday { get; set; }

        [Required]
        [StringLength(10)]
        public string Department { get; set; }

        public int Type { get; set; }

        [StringLength(100)]
        public string Gcmid { get; set; }
    }
}

OpenKy.WebUI/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OpenKy.Domain.Concrete;
using OpenKy.Domain.Entities;
using OpenKy.WebUI.Concrete;

namespace OpenKy.WebUI.Controllers
{
    [Auth(Roles = UserType.Staff | UserType.Professor)]
    public class DepartmentsController : Controller
    {
        private Repository db = new Repository();

        // GET: Departments
        public ActionResult Index()
        {
            return View(db.Department.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Department.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Department department = db.Department.Find(id);
            db.Department.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenKy.WebUI/Controllers/MembersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using OpenKy.Domain.Abstract;
using OpenKy.Domain.Concrete;
using OpenKy.Domain.Entities;
using OpenKy.WebUI.Concrete;
using OpenKy.WebUI.Model;

namespace OpenKy.WebUI.Controllers
{
    [Auth(Roles = UserType.Staff | UserType.Professor)]
    public class MembersController : Controller
    {
        private Repository db = new Repository();
        private IMemberProcessor member_proc;
        private ITypeDefineProcessor typedef_proc;
        private IDepartmentProcessor department_proc;

        public MembersController()
        {
            member_proc = new MemberProc(db);
            typedef_proc = new TypeDefineProc(db);
            department_proc = new DepartmentProc(db);
        }

        // GET: Members
        public ActionResult Index()
        {
            ViewBag.TypeDefines = typedef_proc.GetTypeDefs();
            ViewBag.Departments = department_proc.GetDepartments();
            return View(member_proc.GetMembers().ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = member_proc.GetMember(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        void PushDropdownListItem()
        {
            var lstTypes = typedef_proc.GetTypeDefs().Select(type => new SelectListItem()
            {
                Text = type.Name, Value = type.Type.ToString()
            }).ToList();

            var lstDepartments = department_proc.GetDepartments().Select(department => new SelectListItem()
            {
                Text = "[" + department.Code + "] " + department.Name, Value = department.Code
            }).ToList();

            ViewBag.TypeList = lstTypes;
            ViewBag.DepartmentList = lstDepartments;
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            PushDropdownListItem();
            return View();
        }

        // POST: Members/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Number,Password,Name,Phone,Email,Birthday,Department,Type")] Member member)
        {
            if (ModelState.IsValid)
            {
                if(member_proc.AddMember(member))
                    return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = member_proc.GetMember(id);
            if (member == null)
            {
                return HttpNotFound();
            }

            MemberModel viewmodel = new MemberModel()
            {
                Birthday = member.Birthday,
                Department = member.Department,
                Email = member.Email,
                Name = member.Name,
                Number = member.Number,
                Password = null,
                Phone = member.Phone,
                Type = member.Type
            };

            PushDropdownListItem();

            return View(viewmodel);
        }

        // POST: Members/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Number,Password,Name,Phone,Email,Birthday,Department,Type")] MemberModel member)
        {
            if (ModelState.IsValid)
            {
                Member original = member_proc.GetMember(member.Number);
                if (original == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                if (!string.IsNullOrEmpty(member.Password))
                {
                    string passwd = Util.PasswordCrypt(member.Password);
                    original.Password = passwd;
                }

                original.Name = member.Name;
                original.Phone = member.Phone;
                original.Email = member.Email;
                original.Birthday = member.Birthday;
                original.Department = member.Department;
                original.Type = member.Type;

                if (!member_proc.UpdateMember(member.Number, original))
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = member_proc.GetMember(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (member_proc.DeleteMember(id) == null)
                return HttpNotFound();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenKy.WebUI/Controllers/TypeDefinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OpenKy.Domain.Abstract;
using OpenKy.Domain.Concrete;
using OpenKy.Domain.Entities;
using OpenKy.WebUI.Concrete;

namespace OpenKy.WebUI.Controllers
{
    [Auth(Roles = UserType.Staff | UserType.Professor)]
    public class TypeDefinesController : Controller
    {
        private Repository db = new Repository();
        private ITypeDefineProcessor typedef_proc;

        public TypeDefinesController()
        {
            typedef_proc = new TypeDefineProc(db);
        }

        // GET: TypeDefines
        public ActionResult Index()
        {
            return View(typedef_proc.GetTypeDefs().ToList());
        }

        // GET: TypeDefines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeDefine typeDefine = typedef_proc.GetTypeDef(id.Value);
            if (typeDefine == null)
            {
                return HttpNotFound();
            }
            return View(typeDefine);
        }

        // GET: TypeDefines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeDefines/Create
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Type,Name")] TypeDefine typeDefine)
        {
            if (ModelState.IsValid)
            {
                if(!typedef_proc.UpdateType(typeDefine.Type, typeDefine))
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }

            return View(typeDefine);
        }

        // GET: TypeDefines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeDefine typeDefine = typedef_proc.GetTypeDef(id.Value);
            if (typeDefine == null)
            {
                return HttpNotFound();
            }
            return View(typeDefine);
        }

        // POST: TypeDefines/Edit/5
        // 초과 게시 공격으로부터 보호하려면 바인딩하려는 특정 속성을 사용하도록 설정하십시오. 
        // 자세한 내용은 http://go.microsoft.com/fwlink/?LinkId=317598을(를) 참조하십시오.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Type,Name")] TypeDefine typeDefine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeDefine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(typeDefine);
        }

        // GET: TypeDefines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeDefine typeDefine = typedef_proc.GetTypeDef(id.Value);
            if (typeDefine == null)
            {
                return HttpNotFound();
            }
            return View(typeDefine);
        }

        // POST: TypeDefines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!typedef_proc.DeleteType(id))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenKy.WebUI/Views/Members/Create.cshtml
@using System.Collections.Specialized
@using System.Web.UI.WebControls

@model OpenKy.Domain.Entities.Member

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

<!-- 추가 폼 -->
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Department, ViewBag.DepartmentList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                @Html.ActionLink(" ", "index", "Departments", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, ViewBag.TypeList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                @Html.ActionLink(" ", "index", "TypeDefines", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts
 {
    <!-- DatePicker Show Function -->
    <script src="~/Scripts/util.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

OpenKy.WebUI/Views/Members/Delete.cshtml
@model OpenKy.Domain.Entities.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GcmId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GcmId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OpenKy.WebUI/Views/Members/Details.cshtml
@model OpenKy.Domain.Entities.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GcmId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GcmId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Number }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OpenKy.WebUI/Views/Members/Edit.cshtml
@model OpenKy.WebUI.Model.MemberModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Number)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Department, ViewBag.DepartmentList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                @Html.ActionLink(" ", "index", "Departments", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, ViewBag.TypeList as List<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                @Html.ActionLink(" ", "index", "TypeDefines", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts
 {
    <!-- DatePicker Show Function -->
    <script src="~/Scripts/util.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

OpenKy.WebUI/Views/Members/Index.cshtml
@using OpenKy.Domain.Entities
@model IEnumerable<OpenKy.Domain.Entities.Member>

@{
    
    var departments = ViewBag.Departments as IQueryable<Department>;
    var types = ViewBag.TypeDefines as IQueryable<TypeDefine>;
    
    ViewBag.Title = "Member Table Index";
}

<h2>Member Table Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
            @Html.ActionLink(" ", "index", "Departments", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
            @Html.ActionLink(" ", "index", "TypeDefines", null, new { @class = "glyphicon glyphicon-pencil", target = "_blank" })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{ 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @{
                var d = departments.FirstOrDefault(e=>e.Code == item.Department);
                if (d != null)
                {
                    @Html.Raw(d.Name + "(");
                    @Html.DisplayFor(modelItem => item.Department)
                    @Html.Raw(")");
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Department)
                }
            }
        </td>
        <td>
            @{
                var t = types.FirstOrDefault(e => e.Type == item.Type);
                if(t != null)
                {
                    @Html.Raw(t.Name + "(");
                    @Html.DisplayFor(modelitem => item.Type);
                    @Html.Raw(")")
                }
                else
                {
                    @Html.DisplayFor(modelitem => item.Type);
                }
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Number }) |
            @Html.ActionLink("Details", "Details", new { id=item.Number }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Number })
        </td>
    </tr>
}

</table>
@if (!Model.Any())
{@Html.Raw("항목이 없습니다.")}